// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: fwcheck.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type ProbRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip     string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port   string `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	Result string `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ProbRequest) Reset() {
	*x = ProbRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fwcheck_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProbRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbRequest) ProtoMessage() {}

func (x *ProbRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fwcheck_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbRequest.ProtoReflect.Descriptor instead.
func (*ProbRequest) Descriptor() ([]byte, []int) {
	return file_fwcheck_proto_rawDescGZIP(), []int{0}
}

func (x *ProbRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ProbRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *ProbRequest) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

// The response message containing the greetings
type ProbReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip   string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port string `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *ProbReply) Reset() {
	*x = ProbReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fwcheck_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProbReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbReply) ProtoMessage() {}

func (x *ProbReply) ProtoReflect() protoreflect.Message {
	mi := &file_fwcheck_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbReply.ProtoReflect.Descriptor instead.
func (*ProbReply) Descriptor() ([]byte, []int) {
	return file_fwcheck_proto_rawDescGZIP(), []int{1}
}

func (x *ProbReply) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ProbReply) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

var File_fwcheck_proto protoreflect.FileDescriptor

var file_fwcheck_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x66, 0x77, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x66, 0x77, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x22, 0x49, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x62,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x2f, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x62, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x32, 0x41, 0x0a, 0x07, 0x46, 0x57, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12,
	0x36, 0x0a, 0x08, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x43, 0x50, 0x12, 0x14, 0x2e, 0x66, 0x77,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x12, 0x2e, 0x66, 0x77, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x50, 0x72, 0x6f, 0x62,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x73, 0x74, 0x31, 0x32, 0x33, 0x2f, 0x66, 0x77, 0x63,
	0x68, 0x65, 0x63, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_fwcheck_proto_rawDescOnce sync.Once
	file_fwcheck_proto_rawDescData = file_fwcheck_proto_rawDesc
)

func file_fwcheck_proto_rawDescGZIP() []byte {
	file_fwcheck_proto_rawDescOnce.Do(func() {
		file_fwcheck_proto_rawDescData = protoimpl.X.CompressGZIP(file_fwcheck_proto_rawDescData)
	})
	return file_fwcheck_proto_rawDescData
}

var file_fwcheck_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fwcheck_proto_goTypes = []interface{}{
	(*ProbRequest)(nil), // 0: fwcheck.ProbRequest
	(*ProbReply)(nil),   // 1: fwcheck.ProbReply
}
var file_fwcheck_proto_depIdxs = []int32{
	0, // 0: fwcheck.FWCheck.CheckTCP:input_type -> fwcheck.ProbRequest
	1, // 1: fwcheck.FWCheck.CheckTCP:output_type -> fwcheck.ProbReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fwcheck_proto_init() }
func file_fwcheck_proto_init() {
	if File_fwcheck_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fwcheck_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProbRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fwcheck_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProbReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fwcheck_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fwcheck_proto_goTypes,
		DependencyIndexes: file_fwcheck_proto_depIdxs,
		MessageInfos:      file_fwcheck_proto_msgTypes,
	}.Build()
	File_fwcheck_proto = out.File
	file_fwcheck_proto_rawDesc = nil
	file_fwcheck_proto_goTypes = nil
	file_fwcheck_proto_depIdxs = nil
}
