// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: fwcheck.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FWCheckClient is the client API for FWCheck service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FWCheckClient interface {
	// Sends a greeting
	CheckPort(ctx context.Context, in *ProbRequest, opts ...grpc.CallOption) (*ProbReply, error)
}

type fWCheckClient struct {
	cc grpc.ClientConnInterface
}

func NewFWCheckClient(cc grpc.ClientConnInterface) FWCheckClient {
	return &fWCheckClient{cc}
}

func (c *fWCheckClient) CheckPort(ctx context.Context, in *ProbRequest, opts ...grpc.CallOption) (*ProbReply, error) {
	out := new(ProbReply)
	err := c.cc.Invoke(ctx, "/fwcheck.FWCheck/CheckPort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FWCheckServer is the server API for FWCheck service.
// All implementations must embed UnimplementedFWCheckServer
// for forward compatibility
type FWCheckServer interface {
	// Sends a greeting
	CheckPort(context.Context, *ProbRequest) (*ProbReply, error)
	mustEmbedUnimplementedFWCheckServer()
}

// UnimplementedFWCheckServer must be embedded to have forward compatible implementations.
type UnimplementedFWCheckServer struct {
}

func (UnimplementedFWCheckServer) CheckPort(context.Context, *ProbRequest) (*ProbReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckPort not implemented")
}
func (UnimplementedFWCheckServer) mustEmbedUnimplementedFWCheckServer() {}

// UnsafeFWCheckServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FWCheckServer will
// result in compilation errors.
type UnsafeFWCheckServer interface {
	mustEmbedUnimplementedFWCheckServer()
}

func RegisterFWCheckServer(s grpc.ServiceRegistrar, srv FWCheckServer) {
	s.RegisterService(&FWCheck_ServiceDesc, srv)
}

func _FWCheck_CheckPort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FWCheckServer).CheckPort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fwcheck.FWCheck/CheckPort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FWCheckServer).CheckPort(ctx, req.(*ProbRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FWCheck_ServiceDesc is the grpc.ServiceDesc for FWCheck service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FWCheck_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fwcheck.FWCheck",
	HandlerType: (*FWCheckServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckPort",
			Handler:    _FWCheck_CheckPort_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fwcheck.proto",
}
